# See https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled

enabled: true
exclude:
  - '**/*.patch'
  - '**/node_modules/**/*'
  - '**/vendor/**/*'
  - '.github/workflows/**/*' # https://github.com/restyled-io/restyler/issues/73
changed_paths:
  maximum: 1000
  outcome: error
remote_files: [] # Files to download before restyling.

## Pull Requests
auto: false
commit_template: |
  Restyled by ${restyler.name}
pull_requests: true
comments: true
statuses:
  differences: true
  no_differences: true
  error: true
request_review:
  origin: author
  forked: none
labels:
  - 'Type - Style'
  - 'automerge'
# ignore_labels:
#   - restyled-ignore
restylers_version: stable
restylers:
  - prettier:
      arguments:
        - --config .prettier.json
