name: 'Everything Labeler'
description: 'A superpowered issue and pull request labeler for Github Actions.'
author: 'Videndum'
inputs:
  GITHUB_TOKEN:
    description: 'The GITHUB_TOKEN secret'
    required: true
  config:
    description: 'Config file path'
    default: '.github/labels.json'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'purple'
  icon: 'tag'
